#!/bin/sh

set -e

SCRIPT_DIR=`dirname "${0}"`
source "${SCRIPT_DIR}/lib"

OUTPUT_FILE=`mk_temp_file`

# install jobber file
TMP=`mk_temp_file`
cat > "${TMP}" <<EOF
[prefs]

[jobs]
- name: TestJob
  cmd: date > "${OUTPUT_FILE}"
  time: '*'
  notifyOnError: true
EOF
install_jobber_file "${TMP}"

# wait for job to run
sleep 3

# pause it
jobber pause TestJob >/dev/null
sleep 1

# get latest output
OUTPUT_1=`cat "${OUTPUT_FILE}"`

# wait a little
sleep 5

# check whether it ran again
OUTPUT_2=`cat "${OUTPUT_FILE}"`
assert_equal "${OUTPUT_1}" "${OUTPUT_2}" "Job wasn't paused."

# resume it
jobber resume TestJob >/dev/null

# wait a little
sleep 5

# check whether it ran again
OUTPUT_3=`cat "${OUTPUT_FILE}"`
if [ "${OUTPUT_2}" = "${OUTPUT_3}" ]; then
    fail "Job wasn't resumed."
fi

pass
