#!/bin/sh

# This script checks that Jobber is installed, running, and working correctly.
# It does this by adding a jobber file to the current user and then checking
# whether the job in the jobber file gets executed.

set -e

fail() {
   echo "$1" >&2
   exit 1
}

JOBBER_FILE="${HOME}/.jobber"
OUTPUT_FILE=${HOME}/test_job

if [ -e "${JOBBER_FILE}" ]; then
    fail "${JOBBER_FILE} already exists."
fi
if [ -e "${OUTPUT_FILE}" ]; then
    fail "${OUTPUT_FILE} already exists."
fi

# install jobber file
cat > "${JOBBER_FILE}" <<EOF
---
- name: TestJob
  cmd: echo 'Hello!' > ~/test_job
  time: '*'
EOF
jobber reload
sleep 1

# check whether sure job ran
if [ ! -f "${OUTPUT_FILE}" ]; then
    fail "Job failed to run.  (${OUTPUT_FILE} doesn't exist.)"
elif [ "`cat "${OUTPUT_FILE}"`" != "Hello!" ]; then
    fail "Job failed to run.  (${OUTPUT_FILE} has wrong contents.)"
else
    echo "Success!"
fi

# clean up
rm -f "${JOBBER_FILE}"
jobber reload
rm -f "${OUTPUT_FILE}" 
