# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/jessie64"

  config.vm.network :forwarded_port, guest: 22, host: 2224

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update -y
    apt-get install -y golang python-pip dpkg-dev debhelper dh-systemd
    apt-get upgrade -y
    pip install --upgrade pip
    pip install robotframework
    useradd normuser -m
  SHELL
end
