# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"

  config.vm.network :forwarded_port, guest: 22, host: 2224, id: "ssh"

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update -y
    apt-get install -y golang python-pip dpkg-dev debhelper dh-systemd socat
    sudo pip install robotframework pyyaml
    grep normuser /etc/passwd >/dev/null || useradd normuser -m
  SHELL
end
