# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.network :forwarded_port, guest: 22, host: 2225, id: "ssh"

  config.vm.provision "shell", inline: <<-SHELL
    sudo add-apt-repository -y ppa:gophers/archive
    apt-get update -y
    apt-get install -y golang-1.9-go python-pip dpkg-dev debhelper dh-systemd
    ln -s /usr/lib/go-1.9/bin/go /usr/bin/go
    #apt-get upgrade -y
    pip install --upgrade pip
    pip install robotframework
    grep normuser /etc/passwd >/dev/null || useradd normuser -m
  SHELL
end
