#!/bin/sh

# This script tests the official deployment method
# described on Jobber's website.

# Expected env vars:
#   - SRCDIR
#   - HOME

set -e

PARENT_DIR=`dirname "$0"`

fail() {
   echo "$1" >&2
   exit 1
}

# check prereqs
if [ -z "${SRCDIR}" ]; then
    fail "\"SRCDIR\" is not defined."
elif [ -z "${HOME}" ]; then
    fail "\"HOME\" is not defined."
fi

# compile & install
make -C "${SRCDIR}" install

# make sure it's running
service jobber status

# run test
"${SRCDIR}/test_installation"

# uninstall
make -C "${SRCDIR}" uninstall

# make sure everything is gone
if service jobber status; then
    fail "Jobber service is still running."
fi

# clean up
rm -f "${HOME}/.jobber"

echo "Success!"
exit 0

