# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update -y
    apt-get install -y golang python-pip dpkg-dev debhelper dh-systemd
    apt-get upgrade -y
    pip install --upgrade pip
    pip install robotframework
  SHELL
end
