Document: jobber
Title: Debian jobber Manual
Author: <insert document author here>
Abstract: This manual describes what jobber is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/jobber/jobber.sgml.gz

Format: postscript
Files: /usr/share/doc/jobber/jobber.ps.gz

Format: text
Files: /usr/share/doc/jobber/jobber.text.gz

Format: HTML
Index: /usr/share/doc/jobber/html/index.html
Files: /usr/share/doc/jobber/html/*.html
