# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine36"

  config.vm.network :forwarded_port, guest: 22, host: 2227, id: "ssh"

  config.vm.provision "shell", inline: <<-SHELL
    apk update
    apk upgrade
    apk add make 
    apk add alpine-sdk 
    apk add gcc 
    apk add rsync 
    apk add 'go@community>=1.8'
    addgroup vagrant abuild
    grep normuser /etc/passwd >/dev/null || adduser -D normuser
  SHELL
end
