PACKAGING_SOURCES := \
	Makefile \
	centos_6.7/se_policy/jobber.fc \
	centos_6.7/se_policy/jobber.if \
	centos_6.7/se_policy/jobber.te \
	centos_6.7/jobber_init \
	centos_6.7/jobber.spec \
	centos_6.7/Makefile \
	centos_6.7/pkgrel \
	alpine_3.3/APKBUILD \
	alpine_3.3/jobber.initd \
	alpine_3.3/jobber.post-deinstall \
	alpine_3.3/jobber.post-install \
	alpine_3.3/jobber.post-upgrade \
	alpine_3.3/jobber.pre-deinstall \
	alpine_3.3/Makefile \
	alpine_3.3/pkgrel \
	debian_8.5/debian-pkg/source/format \
	debian_8.5/debian-pkg/changelog \
	debian_8.5/debian-pkg/compat \
	debian_8.5/debian-pkg/control \
	debian_8.5/debian-pkg/copyright \
	debian_8.5/debian-pkg/docs \
	debian_8.5/debian-pkg/jobber.init \
	debian_8.5/debian-pkg/jobber.service \
	debian_8.5/debian-pkg/postinst \
	debian_8.5/debian-pkg/rules \
	debian_8.5/Makefile \
	centos_7/jobber.service \
	centos_7/jobber.spec \
	centos_7/Makefile \
	centos_7/pkgrel